// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUq0Fwz6ubqzKP2Gmn430g8F-cn1Ajc3g',
    appId: '1:287187127448:web:8191d0f72f3eae13c514ed',
    messagingSenderId: '287187127448',
    projectId: 'aikya-platform',
    authDomain: 'aikya-platform.firebaseapp.com',
    storageBucket: 'aikya-platform.firebasestorage.app',
    measurementId: 'G-WTT4W33VXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB63cXtjmlnbhUMDVI_izN9vExtjcFa31w',
    appId: '1:287187127448:android:3d8821abe8b3a696c514ed',
    messagingSenderId: '287187127448',
    projectId: 'aikya-platform',
    storageBucket: 'aikya-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2H-BzKZLMTGxiQ2S7hzNjha1TkD5zlc',
    appId: '1:287187127448:ios:b41a9b5e0d3cb915c514ed',
    messagingSenderId: '287187127448',
    projectId: 'aikya-platform',
    storageBucket: 'aikya-platform.firebasestorage.app',
    iosBundleId: 'com.smvitm.aimlHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUq0Fwz6ubqzKP2Gmn430g8F-cn1Ajc3g',
    appId: '1:287187127448:web:6ec769d9d3bb142ac514ed',
    messagingSenderId: '287187127448',
    projectId: 'aikya-platform',
    authDomain: 'aikya-platform.firebaseapp.com',
    storageBucket: 'aikya-platform.firebasestorage.app',
    measurementId: 'G-50V5YJ6JC0',
  );
}
